package main

import (
	"promo-code-api/db"
	_ "promo-code-api/docs" // docs is generated by Swag CLI, you have to import it.
	"promo-code-api/routers"
)


func main() {
	db.ConnectToDatabase()
	routers.Run()
}