package main

import (
	"log"
	"os"
	"promo-code-api/db"
	_ "promo-code-api/docs" // docs is generated by Swag CLI, you have to import it.
	"promo-code-api/routers"

	"github.com/joho/godotenv"
)

func main() {
	if os.Getenv("GO_ENV") == "" { // if GO_ENV is not set load .env file
		err := godotenv.Load(".env")
  if err != nil {
    log.Fatalf("Error loading .env file")
  }
	}
	db.Setup()
	// connect and pass connection to routers then use gin router.Use(dbconnection)
	// error handling
	routers.Run()
}
