package main

import (
	"promo-code-api/db"
	_ "promo-code-api/docs" // docs is generated by Swag CLI, you have to import it.
	"promo-code-api/routers"
)

func main() {
	// connect and pass connection to routers then use gin router.Use(dbconnection)
	// error handling
	db.ConnectToDatabase()
	routers.Run()
}
