// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves promo code by name"
            }
        },
        "/all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves all promo codes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routers.Data"
                        }
                    }
                }
            }
        },
        "/delete/{name}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Update promo code by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/update/{name}": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "summary": "Update promo code by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        }
    },
    "definitions": {
        "routers.Data": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "format": "float64",
                    "example": 5.54
                },
                "date_from": {
                    "type": "string",
                    "format": "string",
                    "example": "1/12"
                },
                "date_to": {
                    "type": "string",
                    "format": "string",
                    "example": "5/12"
                },
                "name": {
                    "type": "string",
                    "format": "string",
                    "example": "barone"
                },
                "quantity_allocated": {
                    "type": "integer",
                    "format": "int64",
                    "example": 12
                },
                "quantity_available": {
                    "type": "integer",
                    "format": "int64",
                    "example": 5
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:5000",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Promo Code API",
	Description: "This is a simple api server using the gin framework.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
