basePath: /api/v1
definitions:
  promocodes.Promocode:
    properties:
      amount:
        example: 5.54
        format: string
        type: number
      dateFrom:
        example: 1/12
        format: string
        type: string
      dateTo:
        example: 5/12
        format: string
        type: string
      id:
        type: integer
      name:
        example: barone
        format: string
        type: string
      quantityAllocated:
        example: 12
        format: string
        type: integer
      quantityAvailable:
        example: 5
        format: string
        type: integer
    required:
    - amount
    - dateFrom
    - dateTo
    - name
    - quantityAllocated
    - quantityAvailable
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple api server using the gin web framework.
  title: Promo Code API
  version: "1.0"
paths:
  /promo:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promocodes.Promocode'
      summary: Retrieves all promo codes
  /promo/admin:
    post:
      consumes:
      - application/json
      parameters:
      - description: Example Data
        in: body
        name: name,quantityAllocated,quantityAvailable,dateFrom,dateTo,amount
        required: true
        schema:
          $ref: '#/definitions/promocodes.Promocode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promocodes.Promocode'
      summary: Add promo code
  /promo/admin/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      summary: Delete promo code by id
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promocodes.Promocode'
      summary: Retrieves all promo codes
    patch:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: Example Data
        in: body
        name: quantityAllocated,quantityAvailable,dateFrom,dateTo,amount
        required: true
        schema:
          $ref: '#/definitions/promocodes.Promocode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promocodes.Promocode'
      summary: Update promo code by id
  /promo/app/{id}:
    post:
      parameters:
      - description: id
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      summary: Should minus from quantity available as it was purchased
swagger: "2.0"
